/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/connections/codex/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Codex Usage */
        get: operations["codex_usage_api_v1_connections_codex_usage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run Evidence */
        get: operations["run_evidence_api_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pause Run */
        post: operations["pause_run_api_v1_runs__run_id__pause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/session/issue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Issue Pairing */
        post: operations["issue_pairing_api_v1_session_issue_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/session/pair": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pair */
        post: operations["pair_api_v1_session_pair_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Local Status */
        get: operations["local_status_api_v1_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Capability */
        Capability: {
            /** Detail */
            detail: string;
            /** Name */
            name: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "blocked" | "unavailable" | "unverified";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Capabilities */
            capabilities: components["schemas"]["Capability"][];
            /** Capability Digest */
            capability_digest: string;
            /**
             * Readiness
             * @enum {string}
             */
            readiness: "ready" | "degraded" | "blocked";
            /** Version */
            version: string;
        };
        /**
         * KnowledgeKind
         * @enum {string}
         */
        KnowledgeKind: "observed" | "reported" | "inferred" | "verified";
        /** PairRequest */
        PairRequest: {
            /** Nonce */
            nonce: string;
        };
        /** RunEvidenceEventView */
        RunEvidenceEventView: {
            /** Detail */
            detail: string;
            /** Id */
            id: string;
            knowledge_kind: components["schemas"]["KnowledgeKind"];
            /** Seq */
            seq: number;
            /** Title */
            title: string;
        };
        /** RunEvidenceView */
        RunEvidenceView: {
            /** Changed Paths */
            changed_paths: string[];
            /** Codex Thread Id */
            codex_thread_id: string;
            /** Codex Turn Id */
            codex_turn_id: string;
            /** Events */
            events: components["schemas"]["RunEvidenceEventView"][];
            /** Final Snapshot Sha256 */
            final_snapshot_sha256: string;
            /** Initial Snapshot Sha256 */
            initial_snapshot_sha256: string;
            /** Model Id */
            model_id: string;
            /** Project */
            project: string;
            /**
             * Recorded At
             * Format: date-time
             */
            recorded_at: string;
            /** Release Commit */
            release_commit: string;
            /** Run Id */
            run_id: string;
            /**
             * Source
             * @constant
             */
            source: "live_receipt";
            /**
             * Status
             * @constant
             */
            status: "verified";
            /** Title */
            title: string;
            verification: components["schemas"]["RunVerificationView"];
        };
        /** RunVerificationView */
        RunVerificationView: {
            /** Duration Ms */
            duration_ms: number;
            /** Output Sha256 */
            output_sha256: string;
            /** Snapshot Sha256 */
            snapshot_sha256: string;
            /**
             * Status
             * @constant
             */
            status: "passed";
            /** Suite Digest */
            suite_digest: string;
        };
        /** UsageAdviceView */
        UsageAdviceView: {
            /** Checkpoint Requested */
            checkpoint_requested: boolean;
            /**
             * Level
             * @enum {string}
             */
            level: "normal" | "prepare" | "pause" | "critical" | "unknown";
            /** Pause Managed Run Requested */
            pause_managed_run_requested: boolean;
            /** Reason */
            reason: string;
        };
        /** UsageResponse */
        UsageResponse: {
            advice: components["schemas"]["UsageAdviceView"];
            /** Error */
            error: string | null;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            /**
             * Source
             * @constant
             */
            source: "codex-app-server";
            /**
             * State
             * @enum {string}
             */
            state: "known" | "unknown" | "stale" | "unavailable";
            /** Windows */
            windows: components["schemas"]["UsageWindowView"][];
        };
        /** UsageWindowView */
        UsageWindowView: {
            /** Limit Id */
            limit_id: string;
            /** Remaining Percent */
            remaining_percent: number;
            /** Resets At */
            resets_at: number | null;
            /** Used Percent */
            used_percent: number;
            /**
             * Window
             * @enum {string}
             */
            window: "primary" | "secondary";
            /** Window Minutes */
            window_minutes: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    codex_usage_api_v1_connections_codex_usage_get: {
        parameters: {
            query?: never;
            header?: {
                "x-dovet-bridge"?: string | null;
            };
            path?: never;
            cookie?: {
                dovet_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_evidence_api_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-dovet-bridge"?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: {
                dovet_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunEvidenceView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pause_run_api_v1_runs__run_id__pause_post: {
        parameters: {
            query?: never;
            header?: {
                "x-dovet-csrf"?: string | null;
                "x-dovet-bridge"?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: {
                dovet_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    issue_pairing_api_v1_session_issue_post: {
        parameters: {
            query?: never;
            header?: {
                "x-dovet-bridge"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pair_api_v1_session_pair_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PairRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    local_status_api_v1_status_get: {
        parameters: {
            query?: never;
            header?: {
                "x-dovet-bridge"?: string | null;
            };
            path?: never;
            cookie?: {
                dovet_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
